import "../assets/css/styles.scss";
import "swiper/swiper.scss";
import "rc-slider/assets/index.css";
import "react-rater/lib/react-rater.css";

import { Poppins } from "next/font/google";
import Script from "next/script";
import { GA_TRACKING_ID } from "@/utils/gtag";
import ReduxProvider from "@/components/ReduxProvider";
import GAPageViewTracker from "@/components/GAPageViewTracker";
import Layout from "../layouts/Main";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--main-font",
});

const isProduction = process.env.NODE_ENV === "production";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.variable}>
      <head>
        {/* Add font variable globally */}
        <style>{`
          :root {
            --main-font: ${poppins.style.fontFamily};
          }
        `}</style>

        {/* We only want to add the scripts if in production */}
        {isProduction && (
          <>
            {/* Global Site Tag (gtag.js) - Google Analytics */}
            <Script
              async
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_TRACKING_ID}`}
            />
            <Script
              id="gtag-inline-script"
              dangerouslySetInnerHTML={{
                __html: `
                  window.dataLayer = window.dataLayer || [];
                  function gtag(){dataLayer.push(arguments);}
                  gtag('js', new Date());
                  gtag('config', '${GA_TRACKING_ID}', {
                    page_path: window.location.pathname,
                  });
                `,
              }}
            />
          </>
        )}
      </head>
      <body>
        <ReduxProvider>
          <Layout>
           {children}
          </Layout>
        </ReduxProvider>
        {isProduction && <GAPageViewTracker />}
      </body>
    </html>
  );
}