import "../assets/css/styles.scss";
import "swiper/swiper.scss";
import "rc-slider/assets/index.css";
import "react-rater/lib/react-rater.css";

import { Poppins } from "next/font/google";
import { Fragment } from "react";

import ReduxProvider from "@/components/ReduxProvider";
import GtagTracker from "@/components/GtagTracker";
import Layout from "../layouts/Main";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--main-font",
});

// Assuming GA_TRACKING_ID is defined in utils/gtag.ts
import { GA_TRACKING_ID } from "@/utils/gtag";

const isProduction = process.env.NODE_ENV === "production";

export const metadata = {
  title: "Create Next App", // Replace with your actual title
  description: "Generated by create next app", // Replace with your actual description
  icons: {
    icon: "/favicon.ico", // Replace with your actual favicon
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* We only want to add the scripts if in production */}
        {isProduction && (
          <Fragment>
            {/* Global Site Tag (gtag.js) - Google Analytics */}
            <script
              async
              src={`https://www.googletervice.com/gtag/js?id=${GA_TRACKING_ID}`}
            />
            <script
              dangerouslySetInnerHTML={{
                __html: `
                    window.dataLayer = window.dataLayer || [];
                    function gtag(){dataLayer.push(arguments);}
                    gtag('js', new Date());

                    gtag('config', '${GA_TRACKING_ID}', {
                      page_path: window.location.pathname,
                    });
                  `,
              }}
            />
          </Fragment>
        )}
      </head>
      <body className={`${poppins.variable}`}>
        <ReduxProvider>
          <Layout>
            {children}
          </Layout>
          {/* Include the GA tracker client component */}
          {isProduction && <GtagTracker />}
        </ReduxProvider>
      </body>
    </html>
  );
}