import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css'; // Assuming this is the main CSS entry point

import Header from '@/components/header'; // Corrected import path based on structure

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next.js Ecommerce', // Default title from the original layout
  description: 'Generated by create next app', // Keep or update description as needed
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Removed router logic as root layout should be a server component
  // Conditional class based on pathname removed as it's not available in server components

  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Assuming Header is app router compatible or a client component */}
        <Header />
        {/* Main content area - conditional class removed */}
        <main>{children}</main>
      </body>
    </html>
  );
}